name = "cigogne"
version = "4.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Easily migrate your Postgres databases. In Gleam !"
licences = ["MIT"]
repository = { type = "github", user = "Billuc", repo = "cigogne" }
links = [{ title = "Website", href = "https://hexdocs.pm/cigogne/" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

internal_modules = [
  "cigogne/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
pog = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
globlin = ">= 2.0.3 and < 3.0.0"
globlin_fs = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
