# This section will be overridden by eventual users of the library
[database]
# If url is defined, it is used to connect to the database
# url = ""

# If other data in this section is defined, it is used to connect
# Otherwise, we fallback to the DATABASE_URL environment variable
# host = "localhost"
user = "billuc"
# /!\ It is not recommended to have your password there
# password = "postgres"
# port = 5432
name = "cigogne_test"

# This section will be overridden by eventual users of the library
[migration-table]
schema = "test"
# table = "migrations"

[migrations]
migration_folder = "migs"

[migrations.dependencies]

