name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["convert", "convert_json"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.6.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: cd ${{ matrix.package }} && gleam deps download
      - run: cd ${{ matrix.package }} && gleam test
      - run: cd ${{ matrix.package }} && gleam format --check src test
