name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: postgres:17-alpine
      ports:
        - 5432
      env:
        POSTGRES_PASSWORD: 'mysecretpassword'
        POSTGRES_USER: 'lbillaud'
        POSTGRES_DB: 'cigogne_test'
    steps:
      - uses: actions/checkout@v4
      - run: psql --host localhost --user lbillaud -f test/setup_test_db.sql cigogne_test
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
