name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: "mysecretpassword"
          POSTGRES_USER: "billuc"
          POSTGRES_DB: "cigogne_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - run: psql -f test/setup_test_db.sql postgres://billuc:mysecretpassword@localhost:5432/cigogne_test
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: pwd
      - run: ls && ls priv && ls priv/test/migrations
      - run: gleam test
      - run: gleam format --check src test
